module Example.Basic.Db.Entries exposing (Entry, entrySchema, idCol, messageCol, createdAtCol, decoder, all, insert, byId, delete, update)

-- This module was automatically generated by elm-ssr query.
-- Do not edit this file manually.
--
-- Elmto is canonical: use entrySchema + *Col with ElmSsr.Db.Elmto.Query / Repo for rich queries,
-- changesets and constraint-safe writes. The simple CRUD helpers below remain for compatibility.

import ElmSsr.Db.Elmto as Elmto
import Json.Decode as Decode exposing (Decoder)
import Json.Encode as Encode
import ElmSsr.Loader as Loader exposing (Loader)

type alias Entry =
    { id : Int
    , message : String
    , createdAt : String
    }

decoder : Decoder Entry
decoder =
    Decode.map3 Entry
        (Decode.field "id" Decode.int)
        (Decode.field "message" Decode.string)
        (Decode.field "created_at" Decode.string)

entrySchema : Elmto.Schema Entry
entrySchema =
    Elmto.schema "entries" decoder
        |> Elmto.field "id" .id Elmto.int
        |> Elmto.field "message" .message Elmto.string
        |> Elmto.field "created_at" .createdAt Elmto.string

idCol : Elmto.Column Entry Int
idCol =
    Elmto.column "id" Encode.int

messageCol : Elmto.Column Entry String
messageCol =
    Elmto.column "message" Encode.string

createdAtCol : Elmto.Column Entry String
createdAtCol =
    Elmto.column "created_at" Encode.string

all : Loader (List Entry)
all =
    Loader.query
        { sql = "SELECT id, message, created_at FROM entries"
        , params = []
        , decoder = decoder
        }


byId : Int -> Loader (Maybe Entry)
byId idVal =
    Loader.queryOne
        { sql = "SELECT id, message, created_at FROM entries WHERE id = ?"
        , params = [ Encode.int idVal ]
        , decoder = decoder
        }


insert : { message : String } -> Loader { rowsAffected : Int }
insert params =
    Loader.execute
        { sql = "INSERT INTO entries (message) VALUES (?)"
        , params =
            [ Encode.string params.message
            ]
        }


delete : Int -> Loader { rowsAffected : Int }
delete idVal =
    Loader.execute
        { sql = "DELETE FROM entries WHERE id = ?"
        , params = [ Encode.int idVal ]
        }


update : Int -> { message : String, createdAt : String } -> Loader { rowsAffected : Int }
update idVal params =
    Loader.execute
        { sql = "UPDATE entries SET message = ?, created_at = ? WHERE id = ?"
        , params =
            [ Encode.string params.message
            , Encode.string params.createdAt
            , Encode.int idVal
            ]
        }


