module Example.Basic.Db.Entries exposing (Entry, EntriesTable, table, id, message, createdAt, decoder, all, insert, byId, delete, update)

-- This module was automatically generated by elm-ssr query.
-- Do not edit this file manually.

import ElmSsr.Db.Dsl as Dsl exposing (Table, Column)
import Json.Decode as Decode exposing (Decoder)
import Json.Encode as Encode
import ElmSsr.Loader as Loader exposing (Loader)

type EntriesTable
    = EntriesTable


table : Table EntriesTable
table =
    Dsl.table "entries"


id : Column EntriesTable Int
id =
    Dsl.column "id" Encode.int


message : Column EntriesTable String
message =
    Dsl.column "message" Encode.string


createdAt : Column EntriesTable String
createdAt =
    Dsl.column "created_at" Encode.string


type alias Entry =
    { id : Int
    , message : String
    , createdAt : String
    }

decoder : Decoder Entry
decoder =
    Decode.map3 Entry
        (Decode.field "id" Decode.int)
        (Decode.field "message" Decode.string)
        (Decode.field "created_at" Decode.string)

all : Loader (List Entry)
all =
    Loader.query
        { sql = "SELECT id, message, created_at FROM entries"
        , params = []
        , decoder = decoder
        }


byId : Int -> Loader (Maybe Entry)
byId id =
    Loader.queryOne
        { sql = "SELECT id, message, created_at FROM entries WHERE id = ?"
        , params = [ Encode.int id ]
        , decoder = decoder
        }


insert : { message : String } -> Loader { rowsAffected : Int }
insert params =
    Loader.execute
        { sql = "INSERT INTO entries (message) VALUES (?)"
        , params =
            [ Encode.string params.message
            ]
        }


delete : Int -> Loader { rowsAffected : Int }
delete id =
    Loader.execute
        { sql = "DELETE FROM entries WHERE id = ?"
        , params = [ Encode.int id ]
        }


update : Int -> { message : String, createdAt : String } -> Loader { rowsAffected : Int }
update id params =
    Loader.execute
        { sql = "UPDATE entries SET message = ?, created_at = ? WHERE id = ?"
        , params =
            [ Encode.string params.message
            , Encode.string params.createdAt
            , Encode.int id
            ]
        }


